#template modified from: https://docs.docker.com/build/ci/github-actions/multi-platform/
name: "Publish Docker"

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [
          {buildx: linux/amd64, target_arch: amd64},
          {buildx: linux/arm/v7, target_arch: armv7},
          {buildx: linux/arm/v7, target_arch: armhf},
          {buildx: linux/arm64,  target_arch: aarch64}
        ]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            davidusb/emhass-docker-standalone
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform.buildx }}
          build-args: |
            build_version=standalone
            TARGETARCH=${{ matrix.platform.target_arch }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          outputs: type=image,name=davidusb/emhass-docker-standalone,push-by-digest=true,name-canonical=true,push=true
      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"
      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ matrix.platform.target_arch }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1